import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { auth } from "@/auth";

export const metadata: Metadata = {
  title: "login-devlinks",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  console.log(session);
  return (
    <>
      <Navbar sessionUser={session?.user?.email as string} />
      <main>{children}</main>
    </>
  );
}
